version: 2

jobs:
  build:
    docker:
      # the circleci/* images are just too much in this case. I just want
      # jq, git, bash and curl (cimg is also circleci's images) but I gave
      # up since circleci expects so many things on these images. I picked
      # Go since I hope the size of the image isn't too big.
      - image: "cimg/go:1.14"
    environment:
      # These variables are needed by 'c4'. Some of these are stored in
      # Circle CI: GCP_JSON_KEY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY,
      # OS_USERNAME OS_PASSWORD, SLACK_TOKEN.
      AWS_REGION: eu-west-3
      OS_AUTH_URL: "https://auth.cloud.ovh.net"
      OS_PROJECT_NAME: "6371880630829413"
      OS_REGION: UK1
      OS_IDENTITY_API_VERSION: "3"
      OS_PROJECT_DOMAIN_NAME: Default

    steps:
      - checkout
      - run: sudo apt install curl jq
      - run: ./.circleci/gh-dl-release latest c4_linux_amd64 && chmod +x c4_linux_amd64
      - run: ./c4_linux_amd64 --version
      - run: ./c4_linux_amd64 --aws-regex="(test|example)" --os-regex="(test|example)" --gcp-regex="(test|example)" --do-it --older-than=1h --slack-channel=test-channel

workflows:
  version: 2
  nuke_vms:
    jobs:
      - build
    triggers:
      - schedule:
          # Circle CI don't really fully support cron. The */30 (every 30
          # minutes) doesn't work.
          # https://discuss.circleci.com/t/schedule-workflow-doesnt-work/17948/2
          cron: "0,30 * * * *"
          filters:
            branches:
              only:
                - master
                # If you need to test this cron job before it goes to
                # master, you can push to 'branch-for-circle-ci-testing'
                # and it will be run there.
                - branch-for-circle-ci-testing
